# n2bio/peat/Cargo.toml

[package]
name = "peat"
version = "0.1.0"
authors = ["Samuel Bryson <sjbryson@ucla.edu>"]
description = "A cli tool for working with paired-end alignments in sam or bam format."
edition = "2024"
license = "MIT"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
crossbeam = "0.8"
rayon = "1.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lru = "0.18.4"
n2bio = "0.1.1"